// 01010101
#define PAGE_SIZE 128
#define PACKET_HEADER 0x55
#define PACKET_SIZE   PAGE_SIZE+4
enum {
    PACKET_STOP,
    PACKET_LEDTOGGLE,
    PACKET_FORWARDMSG,
    PACKET_FORWARDRAWMSG,
    PACKET_BOOTPAGE
};

typedef enum {
    NORMAL = 0,
    SPECIAL = 0x80,
    BOOT = 0x80,
    BOOTPGM_PAGE,
    BOOTPGM_SIZE,
    RESET,
    SLEEP,
    WAKEUP,
    CHARGE,
    VOLTAGE,
    RUN,
} message_type_t;
